version: "3.7"

services:
  sorcer:
    container_name: sorcer
    image: sorcer
    restart: always
    volumes:       
      - ~/share:/share
    environment:
      - TOKEN=${TOKEN}
      - PASSWORD=${PASSWORD}
    networks: 
      - nginx_network

  nginx-proxy:
    container_name: nginx 
    image: nginx:1.21     
    volumes:       
    # todo remove logs
      - /var/log/nginx:/var/log/nginx       
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/nginx-proxy-server.ru/chain.pem:/etc/nginx/ssl/chain.pem:ro
      - /etc/letsencrypt/live/nginx-proxy-server.ru/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - /etc/letsencrypt/live/nginx-proxy-server.ru/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
      - nginx_cache:/var/cache/nginx
      - ~/share:/usr/share/nginx/html:ro
    ports: 
      - "80:80"
      - "443:443"
    restart: always
    depends_on: 
      - sorcer
    networks: 
      - nginx_network

volumes:
  nginx_cache:

networks: 
  nginx_network: